version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: unless-stopped
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  
  server:
    build: ./userMS
    